---
- name: Setup all hosts with common behaviour
  hosts: all
  roles:
    - common
  tags:
    - common

- name: Setup mosquitto
  # gather_facts: no
  hosts: mosquitto
  roles:
    - mosquitto
  tags:
    - mosquitto